namespace:
  name: demo

image:
  repository: nginx 
  tag: alpine
  pullPolicy: IfNotPresent
  tagName: alpine

resource:
  cpu: "50m"
  mem: "256Mi"

service:
  type: ClusterIP
  port: 8111

replicaCount: 3
